# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Sentry Release

on:
  release:
    types: [created]
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  sentry-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Sentry release
        run: |
            # Install the cli
            curl -sL https://sentry.io/get-cli/ | bash
            
            # Setup configuration values
            VERSION=`sentry-cli releases propose-version`
            
            # Workflow to create releases
            sentry-cli releases new "$VERSION"
            sentry-cli releases set-commits "$VERSION" --auto
            sentry-cli releases finalize "$VERSION"
        env:
          SENTRY_AUTH_TOKEN: 8298aaebeb97fbcd083af484f4844179ff29b4bfdc5c52bf1dd00260175178ae
          SENTRY_ORG: drazisilcom
          SENTRY_PROJECT: rustymotors
